version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
    php:
        build:
            context: .
            dockerfile: ./config/php.dockerfile
            args:
                WORDPRESS: ${WORDPRESS:-false}
        volumes:
            - ./app:/app
            - ./config/scripts:/scripts
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'dbuser'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'app'
        volumes:
            - ./mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
#volumes:
#    mysqldata: {}
