#!/bin/bash
composer create-project -n wintercms/winter /app/code

cd /app/code
# ADD USER PLUGIN
composer require winter/wn-user-plugin dev-main
# ADD TRANSLATE PLUGIN
composer require winter/wn-translate-plugin dev-main
# ADD BUILDER PLUGIN
composer require winter/wn-builder-plugin dev-main
# ADD pages PLUGIN
composer require winter/wn-pages-plugin dev-main
# ADD DEBUG-BAR
composer require winter/wn-debugbar-plugin

php artisan winter:env
cp /scripts/sample.env /app/code/.env
php artisan winter:up 
echo 'Change user:password to admin:admin'
php artisan winter:passwd admin admin
echo "Remove all git related stuff"
( find . -type d -name ".git" && find . -name ".gitmodules" ) | xargs rm -rf
echo "Initialize git repo"
git init
