#!/bin/bash
composer create-project wintercms/winter /app/code "dev-develop"

cd /app/code
php artisan winter:env
cp /scripts/sample.env /app/code/.env
php artisan winter:up 
php artisan winter:passwd admin admin
